/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Get the deserialized value of a key */
export function get(key: string): Promise<any | null>
/** Get the deserialized values of a set of keys */
export function mget(keys: Array<string>): Promise<Array<any | undefined | null>>
/** Serialize and set the value at a key */
export function set(key: string, value?: any | undefined | null): Promise<void>
/** Serialize and set the values of multiple keys */
export function mset(data: Array<[string, any | undefined | null]>): Promise<void>
