/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Get the value at a key and return the deserialized value */
export function get(key: string): Promise<any | null>
/** Set the value at a key */
export function set(key: string, value: any): Promise<void>
